### ISSUE TITLE
Seeing italic fonts, even though I have selected the 'No italics' variant

### ISSUE THREAD

**Issue by ijdickinson** [mao-santaella-rs/NightWolfTheme#24]
**Please make sure you're using the latest version of the plugin before submitting an issue**

I've been using Night-wolf for a while, and I really like it. But I find italicized text distracting, so I use the 'No italics' version. But now I'm seeing italics anyway

**Screenshots**
If applicable, add screenshots to help explain your problem, it helps us debug faster.

![image](https://user-images.githubusercontent.com/63979/76758658-0ffefd00-6782-11ea-95c9-9715d4f8a674.png)

In my Vue.js code:

![image](https://user-images.githubusercontent.com/63979/76758737-3cb31480-6782-11ea-8a57-9e13cf9bef0f.png)

If you are submitting a bug report in a language not currently in demo folder, a PR to this folder with the language helps us track it down.

Thanks!

Version info:
Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:44:52.965Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.3.0-40-generic snap

Night-wolf 1.8.2

**Comment by mao-santaella-rs** [comment]
Hi Ian, thanks for the issue sorry for taking so much time to check out the repo, I'll be looking for this bug and I will let you know whenever I fixed, thanks again

**Comment by mao-santaella-rs** [comment]
Hi, @ijdickinson I just publish v1.8.3 that take care of this issue, thanks again for taking the time to make the issue, let me know if you find anything else wrong with the theme.

**Comment by ijdickinson** [comment]
@mao-santaella-rs Confirm fixed. Thank you!
