### ISSUE TITLE
[Suggestion] Remove saturation spike

### ISSUE THREAD

**Issue by StevenDoesStuffs** [mao-santaella-rs/NightWolfTheme#26]
First, thanks for making this really amazing theme! I was looking for something similar to IntelliJ's material theme, and this fit really well. 
Anyhow, I've used this for a while, and one thing that's always stuck out to me are the cyan and blue colors. They're very attention grabbing, and so I checked the saturation values on these colors, and they're both 100! 
Compare this to the rest of the colors, which range from 40-55 (except magenta 70, and beige at 15), and it really does feel like these colors stick out. I think the theme would look better if we toned them down a little bit. 

Here are my suggestions for the colors:
Blue - #42c6ff (saturation of 74)
Cyan - #38e0e0 (saturation of 75)

Unfortunately I can't provide screenshots as to what those look like (or look at them myself) because I can't figure out how to run the extension after modifying it.

I understand that those two colors might be _intended_ to highlight things that are important (like keywords), but unfortunately they're not always used that way. For example, here's a method I wrote in Rust: https://imgur.com/a/584DEoS.

**Comment by mao-santaella-rs** [comment]
Hi Steven, thank you for taking the time to make this issue and explain it, about the saturation of the colors is actually what I love about the theme, however, I did look at your screenshot and yes the theme is oversaturating that language through painting every word with a color, I think that is the problem too much coloring and no neutral colors, I don't know what language is that but I think it has to be re-think in the theme, what I did is check very thoroughly the languages I develop with and I invite you to make a pr making that language less saturated the way it's doing it in the screenshot.
Thank you again and sorry for the inconvenience.

**Comment by StevenDoesStuffs** [comment]
Ah, I understand. rust-analyzer is fairly new, and it's a plugin that handles the highlighting. I'll take a look on what's going on on their side of things because it does seem strange that everything is highlighted, and although my main problem isn't that everything is highlighted, but rather that the colors which attract the most attention are used for very common things (like identifies), it does seem more like their problem.

**Comment by mao-santaella-rs** [comment]
Thanks for understanding
