### ISSUE TITLE
.gitignored files and folder have the same color as the ones included in the repo

### ISSUE THREAD

**Issue by abhijit-hota** [mao-santaella-rs/NightWolfTheme#28]
**Screenshots**
In the following images, `node_modules` and `debug.log` are in the `.gitignore` file. Generally, VS Code greys out those file and folder names which is handy to ensure that the files are indeed ignored from the repo. 

For **Night Wolf [dark blue]**
![image](https://user-images.githubusercontent.com/8116174/97077330-71345c00-1600-11eb-86d0-65e0724839ab.png)

But that doesn't seem to be the case with **Night Wolf [black]** and **Night Wolf [dark grey]**. I assume they use the same color as the default "ignored files" color.

![image](https://user-images.githubusercontent.com/8116174/97077258-c7ed6600-15ff-11eb-83c0-53a45db18611.png)

Increasing the color contrast between the filenames would fix this.

Thanks for this amazing port of Night Owl!

**Comment by mao-santaella-rs** [comment]
nice catch @abhijit-hota, thanks, working on it

**Comment by mao-santaella-rs** [comment]
@abhijit-hota thanks for taking the time to create this issue it's now fixed in v1.8.5

**Comment by abhijit-hota** [comment]
@mao-santaella-rs You're welcome! Great to hear that it's fixed now. 😄
