### ISSUE TITLE
Better support for rust-lang keyword?

### ISSUE THREAD

**Issue by WindSoilder** [mao-santaella-rs/NightWolfTheme#30]
**Describe the solution you'd like**
Like the following diagram, the keyword `use`, `pub`, `fn`, `as` is not highlighted, it seems that it can be improved?
![图片](https://user-images.githubusercontent.com/22256154/122743648-c02eb000-d2b9-11eb-939f-bad620852600.png)

**Comment by WindSoilder** [comment]
Updated: I have tweaked to use the following setting my self
```json
    "editor.tokenColorCustomizations": {
        "[Night Wolf [dark gray]]": {
            "textMateRules": [
                {
                    "scope": [
                        "keyword"
                    ],
                    "settings": {
                        "foreground": "#00b1ff",
                        "fontStyle": "italic"
                    }
                }
            ]
        }
```

For now it works fine for me, but I still have troble for the `in` operator in `for` loop control...

![图片](https://user-images.githubusercontent.com/22256154/122849633-76d47400-d33e-11eb-9653-d0bbf2b34398.png)

**Comment by mao-santaella-rs** [comment]
Hi @WindSoilder thanks for taking the time to do this, I haven't done anything for rust but I'll be gladly looking into this shortly, thanks again

**Comment by mao-santaella-rs** [comment]
Hi @WindSoilder, thanks again for taking the time, I just updated the theme to v1.9.0 and solves this, please let me know what you think

**Comment by WindSoilder** [comment]
Oh... Thanks for your update :-)  The new version is much better than I expected :-)

Loving the purple color for `use`, `for .. in ..` keyword.  And blue for type define keyword like `fn`, `struct`.

I can't say how much I love these changes!  Anyway, thank you! I love it very much.
