### ISSUE TITLE
More contract on selected text?

### ISSUE THREAD

**Issue by WindSoilder** [mao-santaella-rs/NightWolfTheme#31]
**Describe the solution you'd like**
As in screenshot, I have selected a `float` text, but it seems it's hard to see the `float` text is selected.
![image](https://user-images.githubusercontent.com/22256154/124719677-fa46b580-df39-11eb-97d3-42a3e26d5195.png)

Compared to night owl theme:

![image](https://user-images.githubusercontent.com/22256154/124719801-1ba7a180-df3a-11eb-9ea1-71b65a457b0b.png)

I think it's more clear.

So maybe it's better to add more contract on selected text?

**Comment by mao-santaella-rs** [comment]
Hi @WindSoilder thanks for taking the time to do this, sure I'll take a look a this shortly

**Comment by mao-santaella-rs** [comment]
Hi @WindSoilder, thanks once again for taking the time to make this, this is the only way to see the problems other people are having, I just updated the theme to v1.9.1 and I think solves this, please let me know what you think.

**Comment by WindSoilder** [comment]
Hi, @mao-santaella-rs thanks for your effort on this :-D

It's better than before, but, in personal, I think it's still to low for me.
