### ISSUE TITLE
Selected words contrast being too low.

### ISSUE THREAD

**Issue by grindarius** [mao-santaella-rs/NightWolfTheme#32]
### Versions:
Visual Studio Code 1.58
Night Wolf theme 1.9.1
Using `Night Wolf [black] [no italics]`

![image](https://user-images.githubusercontent.com/60266519/126113793-a98489df-7de4-4d89-8014-506762e17107.png)
In the above image, I am selecting both of the lines with a mouse (click and drag to select code portion). I cannot see the selected portion at all. The above example is from a python file.

![image](https://user-images.githubusercontent.com/60266519/126114846-c3ed4a3f-a912-4d5e-8812-9c1052cfc3e0.png)
For this image, I only select the top line, the bottom line is not selected, and I cannot see the difference between the two.

![image](https://user-images.githubusercontent.com/60266519/126114970-572577cc-ac3f-4148-a827-870c57fc17e7.png)
Example of the problem from a TypeScript file. I only select the function, I did not select the `generateExamples()` line

**Comment by mao-santaella-rs** [comment]
Hi @grindarius, thanks for taking the time to make this issue, I updated the theme to address this in v1.10.0, let me know if fixed for you, thanks again
