### ISSUE TITLE
Color customizations changes not taking effect

### ISSUE THREAD

**Issue by chalop** [mao-santaella-rs/NightWolfTheme#34]
Hello,

There are some slight edits to the colors that I wan't to make for my local version, but the theme doesn't seem to support the [color customizations](https://code.visualstudio.com/docs/getstarted/themes#_workbench-colors) provided by vscode. 

I think is due to the inclusion of the square brackets **[]** in the names of the Night Wolf themes -- I tried changing the color to other templates that don't have the brackets and the customizations worked just fine.

Perhaps replacing the square brackets to parenthesis would be the solution.

Thank you!

**Comment by mao-santaella-rs** [comment]
Hi @chalop thanks for taking the time to do this issue I'll be fixing this in the upcoming days

**Comment by mao-santaella-rs** [comment]
Hi @chalop, thanks for taking the time to make this issue, I updated the theme to address this in v1.11.0, let me know if fixed for you, thanks again
