### ISSUE TITLE
White Svelte components

### ISSUE THREAD

**Issue by afroborg** [mao-santaella-rs/NightWolfTheme#37]
Since the latest update, Svelte components are set to white. 
<img width="207" alt="image" src="https://user-images.githubusercontent.com/23397446/163030647-668c01cb-010d-4d4c-88b3-d9dc2ac7f3f1.png">

Previously they were highlighted as regular HTML, which was fine, but other themes (such as Night Owl) highlights them in a different color which would be nice.
<img width="207" alt="image" src="https://user-images.githubusercontent.com/23397446/163030762-76efd179-a07d-49da-b2cf-74aca5ec13e8.png">

Is this intentional? Components in for example react are styled as regular HTML.

Thanks!

**Comment by mao-santaella-rs** [comment]
wow Hi @afroborg no that definitely is not the intention, can you please send me an example file for svelte and I will definitely fix this, and also what plugins do you use for svelt for better compatibility , thank you very much for taking the time to do this and sorry about that

**Comment by afroborg** [comment]
Great, how about this:

*__layout.svelte:*
```svelte
<script lang="ts" context="module">
	import Navbar from '$/components/layout/navbar.svelte';
</script>

<script lang="ts">
</script>

<div>
	<Navbar />
	<main class="test-class">
		<slot />
	</main>
</div>

<style lang="scss" global>
</style>
```

Im using the [Svelte for VS Code](https://marketplace.visualstudio.com/items?itemName=svelte.svelte-vscode) and [Svelte 3 snippets](https://marketplace.visualstudio.com/items?itemName=fivethree.vscode-svelte-snippets) extensions.

**Comment by mao-santaella-rs** [comment]
Hi @afroborg, thanks for taking the time to make this issue, I updated the theme to address this in v1.11.3, let me know if fixed for you, thanks again

**Comment by afroborg** [comment]
Awesome, works like a charm now, thanks!
