### ISSUE TITLE
Dark css hsl() colors are unreadable in night wolf (dark).

### ISSUE THREAD

**Issue by hansschuijff** [mao-santaella-rs/NightWolfTheme#42]
I use color theme Nigh Wolf Black in vscode and I like it very much. There is just one issue for me, when I code css. When I use the hsl color defs with dark colors it becomes unreadable since the background of the text changes to the color but the font color in the css stays black. Other definitions make the font lighter so it stays readable, but not hsl().

So if I say something like: hsl(0, 0%, 0%) it completely disappears on me and I have change the def to the # color value or rgb or something to make it readable again.

Perhaps something that can be changed? Hope so.

**Comment by mao-santaella-rs** [comment]
Hi @hansschuijff thanks for taking the time to make this issue, the theme is in charge of giving texts colors based on the type of value, so in this case the theme gives the inside values of the hsl a kind of orange color  
![Screenshot 2023-03-18 at 7 55 45 PM](https://user-images.githubusercontent.com/16310596/226147974-b57d9b67-9949-43a4-b4d1-e9d515dd812b.png)
so when you use an extension to give styles to the colors like [Color Highlight](https://marketplace.visualstudio.com/items?itemName=naumovs.color-highlight) the extension is in charge to give these colors based on the value of the hsl.

let me know if you have any other questions, thanks again.
