### ISSUE TITLE
Ruler is black on black in Night Wolf (black)

### ISSUE THREAD

**Issue by landure** [mao-santaella-rs/NightWolfTheme#43]
In VSCode 1.72.2, using Night Wolf (black) v 1.11.5, with VS Code ruler functionality enabled:

In project.code-workspace:

```json
{
  "settings": {
    "editor.rulers": [
       79
    ],
}
```

The ruler is black on black (invisible):

**Screenshots**

Using Nox charcool (amoled):

![image](https://user-images.githubusercontent.com/1490071/196440680-37358b1a-d3e4-4cfa-870a-9893f5a660d6.png)

Using Night Wolf (black):

![image](https://user-images.githubusercontent.com/1490071/196441078-b13ba939-6f13-45a3-9a06-d0af4820a63e.png)

Thank you for your work.

**Comment by mao-santaella-rs** [comment]
Hi @landure, thanks for taking the time to make this issue, I fixed this error in the latest version of the theme (v1.12.0), please make sure it works and let me know if it doesn't.
thanks again and btw sorry for the delay.

**Comment by landure** [comment]
The fix works. Thank you
