### ISSUE TITLE
More visible color to git changes

### ISSUE THREAD

**Issue by matheusf31** [mao-santaella-rs/NightWolfTheme#44]
**Describe the solution you'd like**
A more visible color to git deletions and insertions

**Is your feature request related to a problem? Please describe.**
The color is not visible
![image](https://user-images.githubusercontent.com/45342938/201687704-cba799f5-e59e-441c-b74b-40101f8f2cd2.png)

**Comment by mao-santaella-rs** [comment]
Hi @matheusf31, thanks for taking the time to make this issue, the theme is in charge of assigning the colors for the git deletions and insertions but not the size of the markers on the minimap, however, you can change this in settings with `"editor.minimap.size"` and use the `"fill" || "fit"` value, let me know if you have any other question.

P.D. sorry for the delay on the response

thanks again.
