### ISSUE TITLE
Reserved keywords not properly colored in SQL language

### ISSUE THREAD

**Issue by marcosvnmelo** [mao-santaella-rs/NightWolfTheme#46]
Hi, i really like this theme, but I noticed that the SQL syntax highlighting is not working as expected. Almost all keywords are not colored. For example, see the attached screenshot of a .sql file with Night Wolf theme in comparison to default theme.

| Night Wolf theme | Default theme |
| -------------- | ------------- |
| <img alt="image" src="https://user-images.githubusercontent.com/28654399/232861925-11f5b863-85f6-4fb0-9410-1c85ea8a70af.png"> | <img alt="image" src="https://user-images.githubusercontent.com/28654399/232862073-093d1136-396d-44ee-9201-6ec42b24e4b8.png"> |

I would appreciate it if you could fix this. Thank you for your great work!

**Comment by mao-santaella-rs** [comment]
Hi @marcosvnmelo thanks for taking the time to make this issue. I will take care of this as soon as I have time.

**Comment by mao-santaella-rs** [comment]
Hi @marcosvnmelo if can you create something like a test file for SQL, because I really don't use it, this would help me a lot. thanks

**Comment by marcosvnmelo** [comment]
Hi @mao-santaella-rs the following code has the most used operations in SQL that I could think of: 

```sql

-- Commentary example

CREATE TABLE customers (
    id INTEGER PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE
);

INSERT INTO customers (first_name, last_name, email)
VALUES ('John', 'Doe', 'john.doe@example.com'),
       ('Jane', 'Doe', 'jane.doe@example.com');

SELECT * FROM customers;

UPDATE customers
SET email = 'john.doe@newdomain.com'
WHERE first_name = 'John' AND last_name = 'Doe';

DELETE FROM customers
WHERE first_name = 'Jane' AND last_name = 'Doe';

ALTER TABLE customers
ADD COLUMN phone TEXT;

CREATE INDEX idx_email ON customers (email);

CREATE VIEW customer_info AS
SELECT first_name || ' ' || last_name AS name, email, phone
FROM customers;

SELECT * FROM customer_info;

DROP VIEW customer_info;
```

**Comment by mao-santaella-rs** [comment]
Hi @marcosvnmelo sorry for the delay, I managed to create something for SQL files, however, the syntax highlight support in vscode is very limited, I found an extension that helps with this called [SQL (BigQuery)](https://marketplace.visualstudio.com/items?itemName=shinichi-takii.sql-bigquery), once you have this extension the syntax would look like the images below, but before publishing the new version I would like you to take a look at the colors and tell me if the relationship between the same color words makes sense or if I need to be changed it, what I mean is if the all purple colored words belong like to the same kind of elements or some word make more sense to be red or something like this. thanks for taking the time to respond
![Screenshot 2023-08-31 at 11 51 39 PM](https://github.com/mao-santaella-rs/NightWolfTheme/assets/16310596/83b17e00-ef52-42e7-b180-3e38a6cd1923)
![Screenshot 2023-08-31 at 11 51 53 PM](https://github.com/mao-santaella-rs/NightWolfTheme/assets/16310596/af3955f2-8a92-4849-8910-8130d3d6a5a8)
![Screenshot 2023-08-31 at 11 52 20 PM](https://github.com/mao-santaella-rs/NightWolfTheme/assets/16310596/40e39627-9ed3-486c-8a82-287571cb98c8)

**Comment by marcosvnmelo** [comment]
Hi, @mao-santaella-rs, looks great! Thanks for taking some time to a simple request

**Comment by mao-santaella-rs** [comment]
Perfect! it is coming on the next version
