### ISSUE TITLE
MDX syntax highlighting not working

### ISSUE THREAD

**Issue by preshonyee** [mao-santaella-rs/NightWolfTheme#47]
Hi, I really love this theme, but I noticed that the MDX syntax highlighting is not working as expected. Here's what it looks like compared to other themes - `NightOwl`, `Dark Modern`, `GitHub Dark`.

![CleanShot 2023-10-29 at 15 18 53](https://github.com/mao-santaella-rs/NightWolfTheme/assets/19210093/9bb6e281-0a11-4d73-a0a6-db81b504b39b)

![CleanShot 2023-10-29 at 15 19 34](https://github.com/mao-santaella-rs/NightWolfTheme/assets/19210093/7bc7092a-b848-4e64-88f5-1766c35419f9)

![CleanShot 2023-10-29 at 15 20 28](https://github.com/mao-santaella-rs/NightWolfTheme/assets/19210093/4ed926c0-67f0-4d4c-981c-9d0aa78e2d77)

![CleanShot 2023-10-29 at 15 19 50](https://github.com/mao-santaella-rs/NightWolfTheme/assets/19210093/5811aa0a-aeca-4c3d-a372-11ad4a0c761d)

**Comment by mao-santaella-rs** [comment]
Hi @preshonyee, thank you for bringing this issue to our attention. Currently, our theme does not support MDX. However, we can work together to make it happen. 
- If you could send me an MDX file that contains a broad amount of code to have an example file.
- also if you have a plunging for MDX language support, 
- and if by any chance you have a theme with good support for MDX (this would help a lot).

I can add all the support for it. thanks again for taking the time.

**Comment by mao-santaella-rs** [comment]
closed due to no response
